#site-setting
url : "https://clickmimo.github.io"
github_repository: https://github.com/clickmimo
theme: jekyll-theme-hacker
title: Marin's Blog
description: newbie cyber security enthusiast <b style=\"color: #f45;\">&lt;3</b> 
name: &name "Marin Georgiev"
show_downloads: false
google_analytics: false

#github page setting
github:
  is_project_page: false

#site-author
name : *name 
#bio  : 

#footer
footer_left: 2022 Marin Georgiev
#footer_right: Privacy Policy

#plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed
